# Generated by Django 5.2.17 on 2026-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbetransaction',
            name='cbe_account_target',
            field=models.CharField(default='96072775', help_text='Bank of Abyssinia Target Account', max_length=50),
        ),
        migrations.AlterField(
            model_name='cbetransaction',
            name='cbe_ref_number',
            field=models.CharField(help_text='Bank of Abyssinia Mobile Banking or Transfer Reference Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='payoutlog',
            name='cbe_account',
            field=models.CharField(default='96072775', max_length=50),
        ),
    ]
