# Generated by Django 5.2.17 on 2026-08-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Ethiopian Birr (ETB)', max_digits=10)),
                ('category', models.CharField(choices=[('prompts', 'AI & Business Prompts'), ('templates', 'Ethiopian Business & CV Templates'), ('guides', 'Zero-Capital Earning Guides'), ('software', 'Developer & Freelance Tools')], default='templates', max_length=50)),
                ('content_delivery', models.TextField(help_text='Digital content, download link, or license key delivered upon verification')),
                ('sales_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('UNDER_VERIFICATION', 'Verification Pending'), ('VERIFIED_PAID', 'Verified & Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=30)),
                ('cbe_ref_number', models.CharField(blank=True, help_text='Commercial Bank of Ethiopia Transaction Reference', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='marketplace.product')),
            ],
        ),
    ]
