# Generated by Django 5.2.17 on 2026-08-23 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref_code', models.CharField(max_length=50, unique=True)),
                ('phone_or_bank', models.CharField(help_text='Bank of Abyssinia Account or Phone', max_length=100)),
                ('total_commission_etb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='cbe_ref_number',
            field=models.CharField(blank=True, help_text='Bank of Abyssinia Transaction Reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.affiliate'),
        ),
    ]
