# Generated by Django 5.2.17 on 2026-08-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_affiliate_alter_order_cbe_ref_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Details of what the buyer wants to purchase or get delivered')),
                ('budget_etb', models.DecimalField(decimal_places=2, help_text='Max budget in ETB', max_digits=10)),
                ('delivery_phone', models.CharField(help_text='Phone number for direct phone delivery', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Seller Offers'), ('ACCEPTED', 'Seller Offer Accepted'), ('COMPLETED', 'Fulfilled via Phone/BOA')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=20)),
                ('rental_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending BOA Payment'), ('ACTIVE', 'Active Store Rental'), ('EXPIRED', 'Expired')], default='PENDING_PAYMENT', max_length=30)),
                ('rental_fee_etb', models.DecimalField(decimal_places=2, default=500.0, help_text='Store Rental Fee per month', max_digits=10)),
                ('boa_ref_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=150)),
                ('seller_phone', models.CharField(max_length=20)),
                ('offer_price_etb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_notes', models.TextField(help_text='Phone delivery instructions or download link')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_offers', to='marketplace.buyerproductrequest')),
            ],
        ),
    ]
