# Generated by Django 5.2.17 on 2026-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_buyerproductrequest_vendorstore_selleroffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Direct downloadable PDF document file', null=True, upload_to='pdfs/'),
        ),
    ]
